export { default as ConfirmDeleteDialog } from '../components/ConfirmDeleteDialog.jsx'
export { default as HeaderDashboard } from '../components/HeaderDashboard.jsx'
export { default as HomePage } from './HomePage.jsx'
export { default as SettingsPage } from './SettingsPage.jsx'
export { default as TrendsPage } from './TrendsPage.jsx'